"""Add cover column to Book model

Revision ID: 101ed33ed6f0
Revises: 2e9db879c336
Create Date: 2021-08-23 16:28:03.160617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '101ed33ed6f0'
down_revision = '2e9db879c336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('cover', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'cover')
    # ### end Alembic commands ###
