"""Add cover column to Book model

Revision ID: 707efa5d4061
Revises: 2e9db879c336
Create Date: 2021-08-24 11:03:29.176663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '707efa5d4061'
down_revision = '2e9db879c336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('cover', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'cover')
    # ### end Alembic commands ###
