"""Add confirmed column to User model

Revision ID: 97620963c5f0
Revises: c76ae77770ec
Create Date: 2021-11-10 12:38:31.481750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97620963c5f0'
down_revision = 'c76ae77770ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
